services:
  mongo:
    image: mongo:7
    container_name: cyberyan-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cyberyan_mongo_data:/data/db

volumes:
  cyberyan_mongo_data:
